AllCops:
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 35

Metrics/LineLength:
  AllowURI: true
  Max: 130

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 110
  Exclude:
    - 'test/**/*'