AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 35

Metrics/LineLength:
  AllowURI: true
  Max: 130
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 180
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 8